#ifndef __CONFIG_H__
#define __CONFIG_H__
/*
DEBUG OUTPUT CONFIGURATION
*/

// #define DEBUG_CONSOLE
// #define DEBUG_FILEMAN
// #define DEBUG_FILESERVER
// #define DEBUG_FIRMWARE_STM32
//#define DEBUG_FIRMWARE_WWW
#define DEBUG_LOGTASK
// #define DEBUG_LOGTASK_RX
// #define DEBUG_LOGGING
#define DEBUG_MAIN
// #define DEBUG_REST_SERVER
// #define DEBUG_SETTINGS
// #define DEBUG_SDCARD
// #define DEBUG_SPI_CONTROL
// #define DEBUG_WIFI

#define NUM_CALIBRATION_VALUES 10

/*
    HARDWARE CONFIGURATION
*/


/* STM32 */
#define GPIO_DATA_RDY_PIN 6
#define GPIO_DATA_OVERRUN 10

// SPI
#define STM32_SPI_MOSI 11
#define STM32_SPI_MISO 13
#define STM32_SPI_SCLK 12
#define STM32_SPI_CS 10
#define SPI_STM32_BUS_FREQUENCY 20000000U


#ifdef CONFIG_IDF_TARGET_ESP32
#define STM32_SPI_HOST HSPI_HOST

#else
#define STM32_SPI_HOST SPI3_HOST

#endif


// ADC enable
#define GPIO_ADC_EN 5

// nBOOT0 and nRESET
#define GPIO_STM32_BOOT0 21
#define GPIO_STM32_NRESET 26

#define GPIO_STM32_UART_TX  3 
#define GPIO_STM32_UART_RX  4

/* HMI DISPLAY */
#define GPIO_OLED_SDA 41
#define GPIO_OLED_SCL 42

#define GPIO_HMI_LED_GREEN 38
#define GPIO_HMI_LED_RED 39
#define GPIO_START_STOP_BUTTON 0



#define PROMPT_STR "uberlogger"

/* SD CARD */
#if CONFIG_IDF_TARGET_ESP32 || CONFIG_IDF_TARGET_ESP32S2
#elif CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C2 || CONFIG_IDF_TARGET_ESP32H2
#define GPIO_HANDSHAKE 3
#define STM32_SPI_MOSI 7
#define STM32_SPI_MISO 2
#define STM32_SPI_SCLK 6
#define GPIO_CS 10

#elif CONFIG_IDF_TARGET_ESP32S3
#define GPIO_HANDSHAKE 2
#define STM32_SPI_MOSI 11
#define STM32_SPI_MISO 13
#define STM32_SPI_SCLK 12
#define GPIO_CS 10

#endif //CONFIG_IDF_TARGET_ESP32 || CONFIG_IDF_TARGET_ESP32S2

#define SDCARD_FREE_SPACE_MINIMUM_KB    200
#define SDCARD_FREE_SPACE_WARNING_KB    1024*8
#define SDCARD_SPI_HOST SPI2_HOST


      
#define MAX_SDCARD_SIZE 4000000000
#define MAX_FILE_SIZE MAX_SDCARD_SIZE //  1000000 // 100 MB in bytes

#endif