/*
DEBUG OUTPUT CONFIGURATION
*/

// #define DEBUG_CONSOLE
// #define DEBUG_FILEMAN
#define DEBUG_LOGTASK
#define DEBUG_LOGTASK_RX
// #define DEBUG_LOGGING
#define DEBUG_MAIN
// #define DEBUG_REST_SERVER
// #define DEBUG_SETTINGS
// #define DEBUG_SDCARD
// #define DEBUG_SPI_CONTROL
// #define DEBUG_WIFI


/*
    HARDWARE CONFIGURATION
*/
#if CONFIG_IDF_TARGET_ESP32 || CONFIG_IDF_TARGET_ESP32S2
#define GPIO_DATA_RDY_PIN 6
#define GPIO_DATA_OVERRUN 10

#define STM32_SPI_MOSI 11
#define STM32_SPI_MISO 13
#define STM32_SPI_SCLK 12
#define STM32_SPI_CS 10



#define GPIO_ADC_EN 5

#define GPIO_OLED_SDA 41
#define GPIO_OLED_SCL 42

#define GPIO_HMI_LED 38
#define GPIO_START_STOP_BUTTON 0

#define SPI_STM32_BUS_FREQUENCY 20000000U

#define PROMPT_STR "uberlogger"

#elif CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C2 || CONFIG_IDF_TARGET_ESP32H2
#define GPIO_HANDSHAKE 3
#define STM32_SPI_MOSI 7
#define STM32_SPI_MISO 2
#define STM32_SPI_SCLK 6
#define GPIO_CS 10

#elif CONFIG_IDF_TARGET_ESP32S3
#define GPIO_HANDSHAKE 2
#define STM32_SPI_MOSI 11
#define STM32_SPI_MISO 13
#define STM32_SPI_SCLK 12
#define GPIO_CS 10

#endif //CONFIG_IDF_TARGET_ESP32 || CONFIG_IDF_TARGET_ESP32S2


#ifdef CONFIG_IDF_TARGET_ESP32
#define STM32_SPI_HOST HSPI_HOST

#else
#define STM32_SPI_HOST SPI3_HOST

#endif


/*
SDCARD CONFIGURATION
*/
#define SDCARD_FREE_SPACE_MINIMUM_KB    200
#define SDCARD_FREE_SPACE_WARNING_KB    1024*8
#define SDCARD_SPI_HOST SPI2_HOST